// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Allergyzz",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Allergyzz",
            targets: ["AppModule"],
            bundleIdentifier: "com.sayan.lakhoua.Allergyzz",
            teamIdentifier: "GDB8M9Y3VJ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources/Assets.xcassets"),
                .process("Resources/Fonts"),
                .process("Resources/Sounds"),
                .process("Resources/GIF")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)